-- Dummy Data for Logistik System
-- Period: 25 Jan 2026 - 6 Feb 2026
-- Generated by Antigravity

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Suppliers
INSERT INTO `suppliers` (`id`, `kode_supplier`, `nama_supplier`, `alamat`, `no_telepon`, `email`, `kontak_person`, `is_active`, `created_at`, `updated_at`) VALUES
(10, 'SUP-001', 'PT. Logistik Jaya', 'Jl. Merdeka No. 10, Jakarta', '021-1234567', 'contact@logistikjaya.com', 'Budi Santoso', 1, NOW(), NOW()),
(11, 'SUP-002', 'CV. Sumber Makmur', 'Jl. Sudirman No. 45, Bandung', '022-9876543', 'sales@sumbermakmur.co.id', 'Siti Aminah', 1, NOW(), NOW()),
(12, 'SUP-003', 'UD. Maju Bersama', 'Jl. Ahmad Yani No. 88, Surabaya', '031-5551234', 'info@majubersama.com', 'Rudi Hartono', 1, NOW(), NOW()),
(13, 'SUP-004', 'PT. Teknindo Abadi', 'Jl. Gatot Subroto No. 12, Medan', '061-7778888', 'support@teknindo.com', 'Dewi Lestari', 1, NOW(), NOW()),
(14, 'SUP-005', 'CV. Berkah Alam', 'Jl. Diponegoro No. 5, Semarang', '024-3334444', 'admin@berkahalam.com', 'Agus Setiawan', 1, NOW(), NOW());

-- 2. Permintaan Barang (Requests)
-- Dates: Jan 25 - Jan 30
INSERT INTO `permintaan_barang` (`id`, `kode`, `user_id`, `tanggal`, `alasan`, `status`, `created_at`, `updated_at`) VALUES
(100, 'REQ/202601/100', 1, '2026-01-25', 'Kebutuhan stok bulan Februari', 'disetujui', '2026-01-25 09:00:00', '2026-01-25 10:00:00'),
(101, 'REQ/202601/101', 1, '2026-01-26', 'Restock sparepart mesin', 'diajukan', '2026-01-26 11:30:00', '2026-01-26 11:30:00'),
(102, 'REQ/202601/102', 1, '2026-01-27', 'Permintaan urgent divisi A', 'selesai', '2026-01-27 08:15:00', '2026-01-28 09:00:00'),
(103, 'REQ/202601/103', 1, '2026-01-28', 'Penggantian alat rusak', 'menunggu_persetujuan', '2026-01-28 14:20:00', '2026-01-28 14:20:00'),
(104, 'REQ/202601/104', 1, '2026-01-29', 'Persediaan gudang pusat', 'disetujui', '2026-01-29 10:45:00', '2026-01-29 13:00:00'),
(105, 'REQ/202601/105', 1, '2026-01-30', 'Kebutuhan proyek baru', 'diajukan', '2026-01-30 16:00:00', '2026-01-30 16:00:00');

INSERT INTO `permintaan_barang_detail` (`id`, `permintaan_id`, `barang_id`, `jml`, `jml_approval`, `catatan`) VALUES
(1001, 100, 1001, 10, 10, 'ACC'),
(1002, 100, 1002, 5, 5, 'ACC'),
(1003, 101, 1004, 20, 0, NULL),
(1004, 102, 1005, 50, 50, 'Urgent'),
(1005, 102, 1006, 30, 30, 'Urgent'),
(1006, 103, 1007, 2, 0, 'Cek stok dulu'),
(1007, 104, 1010, 100, 100, 'Okay'),
(1008, 104, 1011, 200, 200, 'Okay'),
(1009, 105, 1013, 15, 0, NULL);

-- 3. Barang Masuk (Inbound)
-- Dates: Jan 26 - Feb 2
INSERT INTO `pencatatan_barang` (`id`, `kode`, `gudang_id`, `jenis`, `tanggal`, `supplier_id`, `user_id`, `sumber_barang`, `created_at`, `updated_at`) VALUES
(200, 'IN/202601/200', 1, 'masuk', '2026-01-26', 10, 1, 'Pembelian PO-001', '2026-01-26 10:00:00', '2026-01-26 10:00:00'),
(201, 'IN/202601/201', 1, 'masuk', '2026-01-27', 11, 1, 'Pembelian PO-002', '2026-01-27 11:00:00', '2026-01-27 11:00:00'),
(202, 'IN/202601/202', 2, 'masuk', '2026-01-29', 12, 1, 'Pembelian PO-003', '2026-01-29 09:30:00', '2026-01-29 09:30:00'),
(203, 'IN/202601/203', 1, 'masuk', '2026-01-31', 13, 1, 'Pembelian PO-004', '2026-01-31 14:15:00', '2026-01-31 14:15:00'),
(204, 'IN/202602/204', 2, 'masuk', '2026-02-02', 14, 1, 'Pembelian PO-005', '2026-02-02 10:00:00', '2026-02-02 10:00:00');

INSERT INTO `pencatatan_barang_detail` (`id`, `pencatatan_id`, `barang_id`, `kondisi`, `jml`, `keterangan`) VALUES
(2001, 200, 1001, 'baik', 100, 'Baru'),
(2002, 200, 1002, 'baik', 50, 'Baru'),
(2003, 201, 1004, 'baik', 200, 'Baru'),
(2004, 202, 1005, 'baik', 500, 'Baru'),
(2005, 203, 1016, 'baik', 50, 'Baru'),
(2006, 204, 1020, 'baik', 100, 'Baru');

-- 4. Barang Keluar (Outbound)
-- Dates: Jan 28 - Feb 5
INSERT INTO `pencatatan_barang` (`id`, `kode`, `gudang_id`, `jenis`, `tanggal`, `user_id`, `tujuan_barang`, `permintaan_id`, `created_at`, `updated_at`) VALUES
(300, 'OUT/202601/300', 1, 'keluar', '2026-01-28', 1, 'Produksi Line 1', 100, '2026-01-28 14:00:00', '2026-01-28 14:00:00'),
(301, 'OUT/202601/301', 1, 'keluar', '2026-01-29', 1, 'Maintenance Team', NULL, '2026-01-29 16:30:00', '2026-01-29 16:30:00'),
(302, 'OUT/202602/302', 1, 'keluar', '2026-02-01', 1, 'Project Alpha', 102, '2026-02-01 09:00:00', '2026-02-01 09:00:00'),
(303, 'OUT/202602/303', 2, 'keluar', '2026-02-03', 1, 'Divisi Umum', NULL, '2026-02-03 11:45:00', '2026-02-03 11:45:00'),
(304, 'OUT/202602/304', 1, 'keluar', '2026-02-05', 1, 'Cabang Bogor', 104, '2026-02-05 13:20:00', '2026-02-05 13:20:00');

INSERT INTO `pencatatan_barang_detail` (`id`, `pencatatan_id`, `barang_id`, `kondisi`, `jml`, `keterangan`) VALUES
(3001, 300, 1001, 'baik', 10, 'Sesuai permintaan'),
(3002, 300, 1002, 'baik', 5, 'Sesuai permintaan'),
(3003, 301, 1016, 'baik', 2, 'Pemakaian rutin'),
(3004, 302, 1005, 'baik', 50, 'Sesuai permintaan'),
(3005, 303, 1020, 'baik', 10, 'Operasional'),
(3006, 304, 1010, 'baik', 100, 'Sesuai permintaan');

-- 5. Transfer Barang
-- Dates: Jan 30 - Feb 4
INSERT INTO `transfer_barang` (`id`, `kode`, `tanggal`, `gudang_asal_id`, `gudang_tujuan_id`, `status`, `user_id`, `diterima_oleh`, `tanggal_diterima`, `catatan`, `created_at`, `updated_at`) VALUES
(400, 'TRF/202601/400', '2026-01-30', 1, 2, 'diterima', 1, 1, '2026-01-30 15:00:00', 'Pemerataan stok', '2026-01-30 08:00:00', '2026-01-30 15:00:00'),
(401, 'TRF/202602/401', '2026-02-02', 1, 2, 'dalam_pengiriman', 1, NULL, NULL, 'Kebutuhan mendesak WH-2', '2026-02-02 09:30:00', '2026-02-02 09:30:00'),
(402, 'TRF/202602/402', '2026-02-04', 2, 1, 'draft', 1, NULL, NULL, 'Kelebihan stok', '2026-02-04 14:00:00', '2026-02-04 14:00:00');

INSERT INTO `transfer_barang_detail` (`id`, `transfer_id`, `barang_id`, `jml_kirim`, `jml_diterima`, `kondisi`, `keterangan`) VALUES
(4001, 400, 1001, 20, 20, 'baik', 'Lengkap'),
(4002, 400, 1004, 50, 50, 'baik', 'Lengkap'),
(4003, 401, 1005, 100, NULL, 'baik', NULL),
(4004, 402, 1020, 30, NULL, 'baik', NULL);

-- 6. Pemeliharaan Barang
-- Dates: Feb 1 - Feb 6
INSERT INTO `pemeliharaan_barang` (`id`, `kode`, `gudang_id`, `status`, `tanggal`, `biaya`, `petugas_id`, `catatan`, `created_at`, `updated_at`) VALUES
(500, 'MTC/202602/500', 1, 'baik', '2026-02-01', 500000.00, 1, 'Service rutin AC Gudang', '2026-02-01 09:00:00', '2026-02-01 11:00:00'),
(501, 'MTC/202602/501', 1, 'diperbaiki', '2026-02-03', 1500000.00, 1, 'Perbaikan Forklift', '2026-02-03 08:30:00', '2026-02-03 08:30:00'),
(502, 'MTC/202602/502', 2, 'baik', '2026-02-05', 250000.00, 1, 'Pengecekan Rak', '2026-02-05 13:00:00', '2026-02-05 14:30:00'),
(503, 'MTC/202602/503', 1, 'rusak', '2026-02-06', 0.00, 1, 'Laporan kerusakan pallet', '2026-02-06 10:00:00', '2026-02-06 10:00:00');

INSERT INTO `pemeliharaan_barang_detaill` (`id`, `pemeliharaan_id`, `barang_id`, `jml`, `keterangan`) VALUES
(5001, 501, 1001, 1, 'Penggantian sparepart'),
(5002, 503, 1004, 5, 'Pallet patah');


-- 7. Stok Gudang (Stock Inventory)
-- Initial Stock for Gudang 1 and 2
INSERT INTO `stok_gudang` (`gudang_id`, `barang_id`, `stok_tersedia`, `stok_minimum`, `stok_maksimum`, `lokasi_rak`, `created_at`, `updated_at`) VALUES
-- Gudang 1
(1, 1001, 1000, 10, 1000, 'A-01-01', NOW(), NOW()), -- SHIM PACK
(1, 1002, 500, 10, 1000, 'A-01-02', NOW(), NOW()), -- CUP,BEARING
(1, 1004, 200, 10, 1000, 'A-01-03', NOW(), NOW()), -- ADAPTER,STRAIGHT
(1, 1005, 800, 10, 1000, 'A-01-04', NOW(), NOW()), -- CONE,BEARING
(1, 1010, 1500, 10, 2000, 'B-02-01', NOW(), NOW()), -- SEAL,LIP
(1, 1011, 2500, 10, 3000, 'B-02-02', NOW(), NOW()), -- BOLT
(1, 1013, 600, 10, 1000, 'B-02-03', NOW(), NOW()), -- WASHER,HARD
(1, 1016, 120, 10, 1000, 'C-03-01', NOW(), NOW()), -- BELT,V
(1, 1020, 400, 10, 1000, 'C-03-02', NOW(), NOW()), -- O-RING

-- Gudang 2
(2, 1001, 200, 10, 1000, 'R-01-01', NOW(), NOW()), -- SHIM PACK (Backup Stock)
(2, 1005, 300, 10, 1000, 'R-01-02', NOW(), NOW()), -- CONE,BEARING
(2, 1020, 100, 10, 1000, 'R-01-03', NOW(), NOW()), -- O-RING
(2, 1023, 50, 10, 1000, 'R-02-01', NOW(), NOW()), -- FILTER,AIR
(2, 1027, 40, 10, 1000, 'R-02-02', NOW(), NOW()), -- FILTER,OIL
(2, 1047, 60, 10, 1000, 'R-02-03', NOW(), NOW()); -- FILTER,FUEL

SET FOREIGN_KEY_CHECKS = 1;
